//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kudotree
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountExperience
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int BusinessId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string JobTitle { get; set; }
        public string ExtraInfo { get; set; }
        public string Description { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Business Business { get; set; }
    }
}
