//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kudotree
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountAssociations = new HashSet<AccountAssociation>();
            this.AccountBusinesses = new HashSet<AccountBusiness>();
            this.AccountConnections = new HashSet<AccountConnection>();
            this.AccountConnections1 = new HashSet<AccountConnection>();
            this.AccountEducations = new HashSet<AccountEducation>();
            this.AccountExperiences = new HashSet<AccountExperience>();
            this.AccountInterests = new HashSet<AccountInterest>();
            this.AccountKudoes = new HashSet<AccountKudo>();
            this.AccountKudoes1 = new HashSet<AccountKudo>();
            this.AccountPosts = new HashSet<AccountPost>();
            this.AccountResumes = new HashSet<AccountResume>();
            this.AccountSkills = new HashSet<AccountSkill>();
            this.AccountTokens = new HashSet<AccountToken>();
            this.Communications = new HashSet<Communication>();
            this.Communications1 = new HashSet<Communication>();
            this.Networks = new HashSet<Network>();
            this.NetworkMembers = new HashSet<NetworkMember>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string JobTitle { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> BusinessOwner { get; set; }
        public Nullable<bool> BusinessOwnerKudoHelp { get; set; }
        public Nullable<bool> JobSeeker { get; set; }
        public Nullable<bool> JobSeekerKudoHelp { get; set; }
        public Nullable<bool> Student { get; set; }
        public Nullable<bool> StudentKudoHelp { get; set; }
        public string ProfilePic { get; set; }
        public string ResumeFile { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public Nullable<bool> TokenExpired { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<AccountAssociation> AccountAssociations { get; set; }
        public virtual ICollection<AccountBusiness> AccountBusinesses { get; set; }
        public virtual ICollection<AccountConnection> AccountConnections { get; set; }
        public virtual ICollection<AccountConnection> AccountConnections1 { get; set; }
        public virtual ICollection<AccountEducation> AccountEducations { get; set; }
        public virtual ICollection<AccountExperience> AccountExperiences { get; set; }
        public virtual ICollection<AccountInterest> AccountInterests { get; set; }
        public virtual ICollection<AccountKudo> AccountKudoes { get; set; }
        public virtual ICollection<AccountKudo> AccountKudoes1 { get; set; }
        public virtual ICollection<AccountPost> AccountPosts { get; set; }
        public virtual ICollection<AccountResume> AccountResumes { get; set; }
        public virtual ICollection<AccountSkill> AccountSkills { get; set; }
        public virtual ICollection<AccountToken> AccountTokens { get; set; }
        public virtual ICollection<Communication> Communications { get; set; }
        public virtual ICollection<Communication> Communications1 { get; set; }
        public virtual ICollection<Network> Networks { get; set; }
        public virtual ICollection<NetworkMember> NetworkMembers { get; set; }
    }
}
