//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kudotree
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAssociation
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int BusinessId { get; set; }
        public int AssociationTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AssociationType AssociationType { get; set; }
        public virtual Business Business { get; set; }
    }
}
