//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kudotree
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.AccountAssociations = new HashSet<AccountAssociation>();
            this.AccountBusinesses = new HashSet<AccountBusiness>();
            this.AccountEducations = new HashSet<AccountEducation>();
            this.AccountExperiences = new HashSet<AccountExperience>();
            this.BusinessProductServices = new HashSet<BusinessProductService>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> CountryId { get; set; }
    
        public virtual ICollection<AccountAssociation> AccountAssociations { get; set; }
        public virtual ICollection<AccountBusiness> AccountBusinesses { get; set; }
        public virtual ICollection<AccountEducation> AccountEducations { get; set; }
        public virtual ICollection<AccountExperience> AccountExperiences { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<BusinessProductService> BusinessProductServices { get; set; }
    }
}
