//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kudotree
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public int Id { get; set; }
        public int CommMethodId { get; set; }
        public int ActionId { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.Guid> ConversationId { get; set; }
        public string Msg { get; set; }
        public Nullable<int> LinkId { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Action Action { get; set; }
        public virtual CommMethod CommMethod { get; set; }
        public virtual Status Status { get; set; }
    }
}
